namespace Trigger
{
    partial class Trigger
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Codes generated by the window designer.

        /// <summary>
        /// The method that used for supporting designer. 
        /// Do not modify the content of this method by code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Trigger));
            this.General = new System.Windows.Forms.GroupBox();
            this.UserDefinedName = new System.Windows.Forms.CheckBox();
            this.PropertSet = new System.Windows.Forms.Button();
            this.StartPlay = new System.Windows.Forms.Button();
            this.ScanDev = new System.Windows.Forms.Button();
            this.OpenDev = new System.Windows.Forms.Button();
            this.DevNameCombo = new System.Windows.Forms.ComboBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.TriggerDelay = new System.Windows.Forms.NumericUpDown();
            this.TriggerLoop = new System.Windows.Forms.NumericUpDown();
            this.ApplyDelay = new System.Windows.Forms.Button();
            this.ApplyLoop = new System.Windows.Forms.Button();
            this.Delay = new System.Windows.Forms.Label();
            this.LoopTimer = new System.Windows.Forms.Label();
            this.SoftTriggerFire = new System.Windows.Forms.Button();
            this.LoopTrigger = new System.Windows.Forms.CheckBox();
            this.TriggerMode = new System.Windows.Forms.CheckBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.EditFilter = new System.Windows.Forms.NumericUpDown();
            this.FilterApply = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.InputSignalTypeCombo = new System.Windows.Forms.ComboBox();
            this.InputIOCombo = new System.Windows.Forms.ComboBox();
            this.InputSignalType = new System.Windows.Forms.Label();
            this.InputIO = new System.Windows.Forms.Label();
            this.EnableIn = new System.Windows.Forms.CheckBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.OutputSignalType = new System.Windows.Forms.ComboBox();
            this.OutIOCombo = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.EnableOut = new System.Windows.Forms.CheckBox();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel4 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel2 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.General.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerDelay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerLoop)).BeginInit();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.EditFilter)).BeginInit();
            this.groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.statusStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.groupBox4.SuspendLayout();
            this.SuspendLayout();
            // 
            // General
            // 
            this.General.Controls.Add(this.UserDefinedName);
            this.General.Controls.Add(this.PropertSet);
            this.General.Controls.Add(this.StartPlay);
            this.General.Controls.Add(this.ScanDev);
            this.General.Controls.Add(this.OpenDev);
            this.General.Controls.Add(this.DevNameCombo);
            this.General.Location = new System.Drawing.Point(2, 150);
            this.General.Name = "General";
            this.General.Size = new System.Drawing.Size(260, 105);
            this.General.TabIndex = 18;
            this.General.TabStop = false;
            this.General.Text = "General";
            // 
            // UserDefinedName
            // 
            this.UserDefinedName.AutoSize = true;
            this.UserDefinedName.Location = new System.Drawing.Point(12, 23);
            this.UserDefinedName.Name = "UserDefinedName";
            this.UserDefinedName.Size = new System.Drawing.Size(119, 17);
            this.UserDefinedName.TabIndex = 24;
            this.UserDefinedName.Text = "User Defined Name";
            this.UserDefinedName.UseVisualStyleBackColor = true;
            this.UserDefinedName.CheckedChanged += new System.EventHandler(this.UserDefineName_CheckedChanged);
            // 
            // PropertSet
            // 
            this.PropertSet.Location = new System.Drawing.Point(187, 73);
            this.PropertSet.Name = "PropertSet";
            this.PropertSet.Size = new System.Drawing.Size(67, 25);
            this.PropertSet.TabIndex = 5;
            this.PropertSet.Text = "Property";
            this.PropertSet.UseVisualStyleBackColor = true;
            this.PropertSet.Click += new System.EventHandler(this.PropertSet_Click);
            // 
            // StartPlay
            // 
            this.StartPlay.Location = new System.Drawing.Point(99, 73);
            this.StartPlay.Name = "StartPlay";
            this.StartPlay.Size = new System.Drawing.Size(80, 25);
            this.StartPlay.TabIndex = 4;
            this.StartPlay.Text = "Start";
            this.StartPlay.UseVisualStyleBackColor = true;
            this.StartPlay.Click += new System.EventHandler(this.StartPlay_Click);
            // 
            // ScanDev
            // 
            this.ScanDev.Location = new System.Drawing.Point(187, 18);
            this.ScanDev.Name = "ScanDev";
            this.ScanDev.Size = new System.Drawing.Size(67, 25);
            this.ScanDev.TabIndex = 3;
            this.ScanDev.Text = "Scan";
            this.ScanDev.UseVisualStyleBackColor = true;
            this.ScanDev.Click += new System.EventHandler(this.ScanDev_Click);
            // 
            // OpenDev
            // 
            this.OpenDev.Location = new System.Drawing.Point(10, 73);
            this.OpenDev.Name = "OpenDev";
            this.OpenDev.Size = new System.Drawing.Size(80, 25);
            this.OpenDev.TabIndex = 2;
            this.OpenDev.Text = "Open";
            this.OpenDev.UseVisualStyleBackColor = true;
            this.OpenDev.Click += new System.EventHandler(this.OpenDev_Click);
            // 
            // DevNameCombo
            // 
            this.DevNameCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DevNameCombo.FormattingEnabled = true;
            this.DevNameCombo.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.DevNameCombo.Location = new System.Drawing.Point(11, 46);
            this.DevNameCombo.Name = "DevNameCombo";
            this.DevNameCombo.Size = new System.Drawing.Size(243, 21);
            this.DevNameCombo.TabIndex = 0;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.TriggerDelay);
            this.groupBox1.Controls.Add(this.TriggerLoop);
            this.groupBox1.Controls.Add(this.ApplyDelay);
            this.groupBox1.Controls.Add(this.ApplyLoop);
            this.groupBox1.Controls.Add(this.Delay);
            this.groupBox1.Controls.Add(this.LoopTimer);
            this.groupBox1.Controls.Add(this.SoftTriggerFire);
            this.groupBox1.Controls.Add(this.LoopTrigger);
            this.groupBox1.Controls.Add(this.TriggerMode);
            this.groupBox1.Location = new System.Drawing.Point(2, 261);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(259, 133);
            this.groupBox1.TabIndex = 19;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Trigger";
            // 
            // TriggerDelay
            // 
            this.TriggerDelay.Location = new System.Drawing.Point(101, 104);
            this.TriggerDelay.Maximum = new decimal(new int[] {
            99999999,
            0,
            0,
            0});
            this.TriggerDelay.Name = "TriggerDelay";
            this.TriggerDelay.Size = new System.Drawing.Size(81, 20);
            this.TriggerDelay.TabIndex = 23;
            // 
            // TriggerLoop
            // 
            this.TriggerLoop.Location = new System.Drawing.Point(101, 74);
            this.TriggerLoop.Maximum = new decimal(new int[] {
            99999999,
            0,
            0,
            0});
            this.TriggerLoop.Name = "TriggerLoop";
            this.TriggerLoop.Size = new System.Drawing.Size(81, 20);
            this.TriggerLoop.TabIndex = 23;
            // 
            // ApplyDelay
            // 
            this.ApplyDelay.Location = new System.Drawing.Point(187, 104);
            this.ApplyDelay.Name = "ApplyDelay";
            this.ApplyDelay.Size = new System.Drawing.Size(66, 23);
            this.ApplyDelay.TabIndex = 8;
            this.ApplyDelay.Text = "Apply";
            this.ApplyDelay.UseVisualStyleBackColor = true;
            this.ApplyDelay.Click += new System.EventHandler(this.ApplyDelay_Click);
            // 
            // ApplyLoop
            // 
            this.ApplyLoop.Location = new System.Drawing.Point(187, 74);
            this.ApplyLoop.Name = "ApplyLoop";
            this.ApplyLoop.Size = new System.Drawing.Size(66, 23);
            this.ApplyLoop.TabIndex = 7;
            this.ApplyLoop.Text = "Apply";
            this.ApplyLoop.UseVisualStyleBackColor = true;
            this.ApplyLoop.Click += new System.EventHandler(this.ApplyLoop_Click);
            // 
            // Delay
            // 
            this.Delay.AutoSize = true;
            this.Delay.Location = new System.Drawing.Point(10, 108);
            this.Delay.Name = "Delay";
            this.Delay.Size = new System.Drawing.Size(51, 13);
            this.Delay.TabIndex = 4;
            this.Delay.Text = "Delay(us)";
            // 
            // LoopTimer
            // 
            this.LoopTimer.AutoSize = true;
            this.LoopTimer.Location = new System.Drawing.Point(10, 79);
            this.LoopTimer.Name = "LoopTimer";
            this.LoopTimer.Size = new System.Drawing.Size(77, 13);
            this.LoopTimer.TabIndex = 3;
            this.LoopTimer.Text = "Loop Timer(us)";
            // 
            // SoftTriggerFire
            // 
            this.SoftTriggerFire.Location = new System.Drawing.Point(129, 17);
            this.SoftTriggerFire.Name = "SoftTriggerFire";
            this.SoftTriggerFire.Size = new System.Drawing.Size(124, 25);
            this.SoftTriggerFire.TabIndex = 2;
            this.SoftTriggerFire.Text = "Soft Trigger Fire";
            this.SoftTriggerFire.UseVisualStyleBackColor = true;
            this.SoftTriggerFire.Click += new System.EventHandler(this.SoftTriggerFire_Click);
            // 
            // LoopTrigger
            // 
            this.LoopTrigger.AutoSize = true;
            this.LoopTrigger.Location = new System.Drawing.Point(11, 46);
            this.LoopTrigger.Name = "LoopTrigger";
            this.LoopTrigger.Size = new System.Drawing.Size(83, 17);
            this.LoopTrigger.TabIndex = 1;
            this.LoopTrigger.Text = "LoopTrigger";
            this.LoopTrigger.UseVisualStyleBackColor = true;
            this.LoopTrigger.CheckedChanged += new System.EventHandler(this.LoopTrigger_CheckedChanged);
            // 
            // TriggerMode
            // 
            this.TriggerMode.AutoSize = true;
            this.TriggerMode.Location = new System.Drawing.Point(11, 22);
            this.TriggerMode.Name = "TriggerMode";
            this.TriggerMode.Size = new System.Drawing.Size(86, 17);
            this.TriggerMode.TabIndex = 0;
            this.TriggerMode.Text = "TriggerMode";
            this.TriggerMode.UseVisualStyleBackColor = true;
            this.TriggerMode.CheckedChanged += new System.EventHandler(this.TriggerMode_CheckedChanged);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.EditFilter);
            this.groupBox2.Controls.Add(this.FilterApply);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.InputSignalTypeCombo);
            this.groupBox2.Controls.Add(this.InputIOCombo);
            this.groupBox2.Controls.Add(this.InputSignalType);
            this.groupBox2.Controls.Add(this.InputIO);
            this.groupBox2.Controls.Add(this.EnableIn);
            this.groupBox2.Location = new System.Drawing.Point(3, 401);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(259, 143);
            this.groupBox2.TabIndex = 20;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Ext Trigger In";
            // 
            // EditFilter
            // 
            this.EditFilter.Location = new System.Drawing.Point(123, 106);
            this.EditFilter.Maximum = new decimal(new int[] {
            99999999,
            0,
            0,
            0});
            this.EditFilter.Name = "EditFilter";
            this.EditFilter.Size = new System.Drawing.Size(57, 20);
            this.EditFilter.TabIndex = 23;
            // 
            // FilterApply
            // 
            this.FilterApply.Location = new System.Drawing.Point(187, 106);
            this.FilterApply.Name = "FilterApply";
            this.FilterApply.Size = new System.Drawing.Size(66, 25);
            this.FilterApply.TabIndex = 7;
            this.FilterApply.Text = "Apply";
            this.FilterApply.UseVisualStyleBackColor = true;
            this.FilterApply.Click += new System.EventHandler(this.FilterApply_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(10, 111);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(71, 13);
            this.label5.TabIndex = 5;
            this.label5.Text = "Jitter Filter(us)";
            // 
            // InputSignalTypeCombo
            // 
            this.InputSignalTypeCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.InputSignalTypeCombo.FormattingEnabled = true;
            this.InputSignalTypeCombo.Location = new System.Drawing.Point(152, 76);
            this.InputSignalTypeCombo.Name = "InputSignalTypeCombo";
            this.InputSignalTypeCombo.Size = new System.Drawing.Size(100, 21);
            this.InputSignalTypeCombo.TabIndex = 4;
            this.InputSignalTypeCombo.SelectedIndexChanged += new System.EventHandler(this.InputSignalTypeCombo_SelectedIndexChanged);
            // 
            // InputIOCombo
            // 
            this.InputIOCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.InputIOCombo.FormattingEnabled = true;
            this.InputIOCombo.Location = new System.Drawing.Point(152, 48);
            this.InputIOCombo.Name = "InputIOCombo";
            this.InputIOCombo.Size = new System.Drawing.Size(100, 21);
            this.InputIOCombo.TabIndex = 3;
            this.InputIOCombo.SelectedIndexChanged += new System.EventHandler(this.InputIOCombo_SelectedIndexChanged);
            // 
            // InputSignalType
            // 
            this.InputSignalType.AutoSize = true;
            this.InputSignalType.Location = new System.Drawing.Point(10, 81);
            this.InputSignalType.Name = "InputSignalType";
            this.InputSignalType.Size = new System.Drawing.Size(90, 13);
            this.InputSignalType.TabIndex = 2;
            this.InputSignalType.Text = "Input Signal Type";
            // 
            // InputIO
            // 
            this.InputIO.AutoSize = true;
            this.InputIO.Location = new System.Drawing.Point(10, 52);
            this.InputIO.Name = "InputIO";
            this.InputIO.Size = new System.Drawing.Size(45, 13);
            this.InputIO.TabIndex = 1;
            this.InputIO.Text = "Input IO";
            // 
            // EnableIn
            // 
            this.EnableIn.AutoSize = true;
            this.EnableIn.Location = new System.Drawing.Point(11, 23);
            this.EnableIn.Name = "EnableIn";
            this.EnableIn.Size = new System.Drawing.Size(59, 17);
            this.EnableIn.TabIndex = 0;
            this.EnableIn.Text = "Enable";
            this.EnableIn.UseVisualStyleBackColor = true;
            this.EnableIn.CheckedChanged += new System.EventHandler(this.EnableIn_CheckedChanged);
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.OutputSignalType);
            this.groupBox3.Controls.Add(this.OutIOCombo);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Controls.Add(this.EnableOut);
            this.groupBox3.Location = new System.Drawing.Point(3, 551);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(259, 101);
            this.groupBox3.TabIndex = 21;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Ext Strobe Out";
            // 
            // OutputSignalType
            // 
            this.OutputSignalType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.OutputSignalType.FormattingEnabled = true;
            this.OutputSignalType.Location = new System.Drawing.Point(151, 66);
            this.OutputSignalType.Name = "OutputSignalType";
            this.OutputSignalType.Size = new System.Drawing.Size(100, 21);
            this.OutputSignalType.TabIndex = 4;
            this.OutputSignalType.SelectedIndexChanged += new System.EventHandler(this.OutputSignalType_SelectedIndexChanged);
            // 
            // OutIOCombo
            // 
            this.OutIOCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.OutIOCombo.FormattingEnabled = true;
            this.OutIOCombo.Location = new System.Drawing.Point(151, 38);
            this.OutIOCombo.Name = "OutIOCombo";
            this.OutIOCombo.Size = new System.Drawing.Size(100, 21);
            this.OutIOCombo.TabIndex = 3;
            this.OutIOCombo.SelectedIndexChanged += new System.EventHandler(this.OutIOCombo_SelectedIndexChanged);
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(10, 70);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(98, 13);
            this.label7.TabIndex = 2;
            this.label7.Text = "Output Signal Type";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(10, 47);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(53, 13);
            this.label8.TabIndex = 1;
            this.label8.Text = "Output IO";
            // 
            // EnableOut
            // 
            this.EnableOut.AutoSize = true;
            this.EnableOut.Location = new System.Drawing.Point(11, 24);
            this.EnableOut.Name = "EnableOut";
            this.EnableOut.Size = new System.Drawing.Size(59, 17);
            this.EnableOut.TabIndex = 0;
            this.EnableOut.Text = "Enable";
            this.EnableOut.UseVisualStyleBackColor = true;
            this.EnableOut.CheckedChanged += new System.EventHandler(this.EnableOut_CheckedChanged);
            // 
            // pictureBox
            // 
            this.pictureBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.pictureBox.Location = new System.Drawing.Point(272, 10);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(804, 643);
            this.pictureBox.TabIndex = 22;
            this.pictureBox.TabStop = false;
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel4,
            this.toolStripStatusLabel1,
            this.toolStripStatusLabel2,
            this.toolStripStatusLabel3});
            this.statusStrip1.Location = new System.Drawing.Point(0, 758);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(1084, 22);
            this.statusStrip1.TabIndex = 27;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel4
            // 
            this.toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.Size = new System.Drawing.Size(69, 17);
            this.toolStripStatusLabel4.Text = "Powered by";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(30, 17);
            this.toolStripStatusLabel1.Text = "RSA";
            // 
            // toolStripStatusLabel2
            // 
            this.toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            this.toolStripStatusLabel2.Size = new System.Drawing.Size(10, 17);
            this.toolStripStatusLabel2.Text = "|";
            // 
            // toolStripStatusLabel3
            // 
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(50, 17);
            this.toolStripStatusLabel3.Text = "Ver 0.0.1";
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(213)))), ((int)(((byte)(28)))));
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(11, 10);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(250, 134);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 26;
            this.pictureBox1.TabStop = false;
            // 
            // textBox1
            // 
            this.textBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox1.Font = new System.Drawing.Font("B Nazanin", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.textBox1.Location = new System.Drawing.Point(3, 16);
            this.textBox1.Multiline = true;
            this.textBox1.Name = "textBox1";
            this.textBox1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.textBox1.Size = new System.Drawing.Size(798, 68);
            this.textBox1.TabIndex = 28;
            this.textBox1.Text = "آدرس گیرنده";
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox4.Controls.Add(this.textBox1);
            this.groupBox4.Location = new System.Drawing.Point(272, 659);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(804, 87);
            this.groupBox4.TabIndex = 29;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Persian OCR result address:";
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("B Titr", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.label1.Location = new System.Drawing.Point(8, 659);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(258, 84);
            this.label1.TabIndex = 30;
            this.label1.Text = "منطقه ؟";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // Trigger
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1084, 780);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.General);
            this.Name = "Trigger";
            this.Text = "RSA Trigger";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Trigger_FormClosing);
            this.Resize += new System.EventHandler(this.Trigger_Resize);
            this.General.ResumeLayout(false);
            this.General.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerDelay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerLoop)).EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.EditFilter)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox General;
        private System.Windows.Forms.Button PropertSet;
        private System.Windows.Forms.Button StartPlay;
        private System.Windows.Forms.Button ScanDev;
        private System.Windows.Forms.Button OpenDev;
        private System.Windows.Forms.ComboBox DevNameCombo;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button ApplyDelay;
        private System.Windows.Forms.Button ApplyLoop;
        private System.Windows.Forms.Label Delay;
        private System.Windows.Forms.Label LoopTimer;
        private System.Windows.Forms.Button SoftTriggerFire;
        private System.Windows.Forms.CheckBox LoopTrigger;
        private System.Windows.Forms.CheckBox TriggerMode;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Button FilterApply;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.ComboBox InputSignalTypeCombo;
        private System.Windows.Forms.ComboBox InputIOCombo;
        private System.Windows.Forms.Label InputSignalType;
        private System.Windows.Forms.Label InputIO;
        private System.Windows.Forms.CheckBox EnableIn;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.ComboBox OutputSignalType;
        private System.Windows.Forms.ComboBox OutIOCombo;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.CheckBox EnableOut;
        private System.Windows.Forms.PictureBox pictureBox;
        private System.Windows.Forms.NumericUpDown TriggerLoop;
        private System.Windows.Forms.NumericUpDown TriggerDelay;
        private System.Windows.Forms.NumericUpDown EditFilter;
		private System.Windows.Forms.CheckBox UserDefinedName;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel4;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel2;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel3;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Label label1;
    }
}

