namespace Trigger
{
    partial class Trigger
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Codes generated by the window designer.

        /// <summary>
        /// The method that used for supporting designer. 
        /// Do not modify the content of this method by code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Trigger));
            this.General = new System.Windows.Forms.GroupBox();
            this.UserDefinedName = new System.Windows.Forms.CheckBox();
            this.PropertSet = new System.Windows.Forms.Button();
            this.StartPlay = new System.Windows.Forms.Button();
            this.ScanDev = new System.Windows.Forms.Button();
            this.OpenDev = new System.Windows.Forms.Button();
            this.DevNameCombo = new System.Windows.Forms.ComboBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.TriggerDelay = new System.Windows.Forms.NumericUpDown();
            this.TriggerLoop = new System.Windows.Forms.NumericUpDown();
            this.ApplyDelay = new System.Windows.Forms.Button();
            this.ApplyLoop = new System.Windows.Forms.Button();
            this.Delay = new System.Windows.Forms.Label();
            this.LoopTimer = new System.Windows.Forms.Label();
            this.SoftTriggerFire = new System.Windows.Forms.Button();
            this.LoopTrigger = new System.Windows.Forms.CheckBox();
            this.TriggerMode = new System.Windows.Forms.CheckBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.EditFilter = new System.Windows.Forms.NumericUpDown();
            this.FilterApply = new System.Windows.Forms.Button();
            this.label5 = new System.Windows.Forms.Label();
            this.InputSignalTypeCombo = new System.Windows.Forms.ComboBox();
            this.InputIOCombo = new System.Windows.Forms.ComboBox();
            this.InputSignalType = new System.Windows.Forms.Label();
            this.InputIO = new System.Windows.Forms.Label();
            this.EnableIn = new System.Windows.Forms.CheckBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.OutputSignalType = new System.Windows.Forms.ComboBox();
            this.OutIOCombo = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.EnableOut = new System.Windows.Forms.CheckBox();
            this.pictureBoxMain = new System.Windows.Forms.PictureBox();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel4 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel2 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.فایلToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ذخیرهگزارشدراکسلToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem3 = new System.Windows.Forms.ToolStripSeparator();
            this.خروجToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ابزارToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.تستارتباطباEcourierToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem1 = new System.Windows.Forms.ToolStripSeparator();
            this.menuLog = new System.Windows.Forms.ToolStripMenuItem();
            this.پاککردنلاگترازوToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem2 = new System.Windows.Forms.ToolStripSeparator();
            this.فایلهایپیکربندیToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.دیتابیسToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.تنظیماتToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem4 = new System.Windows.Forms.ToolStripSeparator();
            this.صفرکردنشمارندهToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolNotMazadCounter = new System.Windows.Forms.ToolStripMenuItem();
            this.کمکToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.دربارهماToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label13 = new System.Windows.Forms.Label();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.picVolume = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.picLogo = new System.Windows.Forms.PictureBox();
            this.picOnOff = new System.Windows.Forms.PictureBox();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.General.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerDelay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerLoop)).BeginInit();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.EditFilter)).BeginInit();
            this.groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxMain)).BeginInit();
            this.statusStrip1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picVolume)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.picOnOff)).BeginInit();
            this.groupBox5.SuspendLayout();
            this.SuspendLayout();
            // 
            // General
            // 
            this.General.Controls.Add(this.UserDefinedName);
            this.General.Controls.Add(this.PropertSet);
            this.General.Controls.Add(this.StartPlay);
            this.General.Controls.Add(this.ScanDev);
            this.General.Controls.Add(this.OpenDev);
            this.General.Controls.Add(this.DevNameCombo);
            this.General.Location = new System.Drawing.Point(6, 110);
            this.General.Name = "General";
            this.General.Size = new System.Drawing.Size(260, 105);
            this.General.TabIndex = 18;
            this.General.TabStop = false;
            this.General.Text = "General";
            // 
            // UserDefinedName
            // 
            this.UserDefinedName.AutoSize = true;
            this.UserDefinedName.Location = new System.Drawing.Point(12, 23);
            this.UserDefinedName.Name = "UserDefinedName";
            this.UserDefinedName.Size = new System.Drawing.Size(119, 17);
            this.UserDefinedName.TabIndex = 24;
            this.UserDefinedName.Text = "User Defined Name";
            this.UserDefinedName.UseVisualStyleBackColor = true;
            this.UserDefinedName.CheckedChanged += new System.EventHandler(this.UserDefineName_CheckedChanged);
            // 
            // PropertSet
            // 
            this.PropertSet.Location = new System.Drawing.Point(187, 73);
            this.PropertSet.Name = "PropertSet";
            this.PropertSet.Size = new System.Drawing.Size(67, 25);
            this.PropertSet.TabIndex = 5;
            this.PropertSet.Text = "Property";
            this.PropertSet.UseVisualStyleBackColor = true;
            this.PropertSet.Click += new System.EventHandler(this.PropertSet_Click);
            // 
            // StartPlay
            // 
            this.StartPlay.Location = new System.Drawing.Point(99, 73);
            this.StartPlay.Name = "StartPlay";
            this.StartPlay.Size = new System.Drawing.Size(80, 25);
            this.StartPlay.TabIndex = 4;
            this.StartPlay.Text = "Start";
            this.StartPlay.UseVisualStyleBackColor = true;
            this.StartPlay.Click += new System.EventHandler(this.StartPlay_Click);
            // 
            // ScanDev
            // 
            this.ScanDev.Location = new System.Drawing.Point(187, 18);
            this.ScanDev.Name = "ScanDev";
            this.ScanDev.Size = new System.Drawing.Size(67, 25);
            this.ScanDev.TabIndex = 3;
            this.ScanDev.Text = "Scan";
            this.ScanDev.UseVisualStyleBackColor = true;
            this.ScanDev.Click += new System.EventHandler(this.ScanDev_Click);
            // 
            // OpenDev
            // 
            this.OpenDev.Location = new System.Drawing.Point(10, 73);
            this.OpenDev.Name = "OpenDev";
            this.OpenDev.Size = new System.Drawing.Size(80, 25);
            this.OpenDev.TabIndex = 2;
            this.OpenDev.Text = "Open";
            this.OpenDev.UseVisualStyleBackColor = true;
            this.OpenDev.Click += new System.EventHandler(this.OpenDev_Click);
            // 
            // DevNameCombo
            // 
            this.DevNameCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DevNameCombo.FormattingEnabled = true;
            this.DevNameCombo.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.DevNameCombo.Location = new System.Drawing.Point(11, 46);
            this.DevNameCombo.Name = "DevNameCombo";
            this.DevNameCombo.Size = new System.Drawing.Size(243, 21);
            this.DevNameCombo.TabIndex = 0;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.TriggerDelay);
            this.groupBox1.Controls.Add(this.TriggerLoop);
            this.groupBox1.Controls.Add(this.ApplyDelay);
            this.groupBox1.Controls.Add(this.ApplyLoop);
            this.groupBox1.Controls.Add(this.Delay);
            this.groupBox1.Controls.Add(this.LoopTimer);
            this.groupBox1.Controls.Add(this.SoftTriggerFire);
            this.groupBox1.Controls.Add(this.LoopTrigger);
            this.groupBox1.Controls.Add(this.TriggerMode);
            this.groupBox1.Location = new System.Drawing.Point(6, 221);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(259, 133);
            this.groupBox1.TabIndex = 19;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Trigger";
            // 
            // TriggerDelay
            // 
            this.TriggerDelay.Location = new System.Drawing.Point(101, 104);
            this.TriggerDelay.Maximum = new decimal(new int[] {
            99999999,
            0,
            0,
            0});
            this.TriggerDelay.Name = "TriggerDelay";
            this.TriggerDelay.Size = new System.Drawing.Size(81, 20);
            this.TriggerDelay.TabIndex = 23;
            // 
            // TriggerLoop
            // 
            this.TriggerLoop.Location = new System.Drawing.Point(101, 74);
            this.TriggerLoop.Maximum = new decimal(new int[] {
            99999999,
            0,
            0,
            0});
            this.TriggerLoop.Name = "TriggerLoop";
            this.TriggerLoop.Size = new System.Drawing.Size(81, 20);
            this.TriggerLoop.TabIndex = 23;
            // 
            // ApplyDelay
            // 
            this.ApplyDelay.Location = new System.Drawing.Point(187, 104);
            this.ApplyDelay.Name = "ApplyDelay";
            this.ApplyDelay.Size = new System.Drawing.Size(66, 23);
            this.ApplyDelay.TabIndex = 8;
            this.ApplyDelay.Text = "Apply";
            this.ApplyDelay.UseVisualStyleBackColor = true;
            this.ApplyDelay.Click += new System.EventHandler(this.ApplyDelay_Click);
            // 
            // ApplyLoop
            // 
            this.ApplyLoop.Location = new System.Drawing.Point(187, 74);
            this.ApplyLoop.Name = "ApplyLoop";
            this.ApplyLoop.Size = new System.Drawing.Size(66, 23);
            this.ApplyLoop.TabIndex = 7;
            this.ApplyLoop.Text = "Apply";
            this.ApplyLoop.UseVisualStyleBackColor = true;
            this.ApplyLoop.Click += new System.EventHandler(this.ApplyLoop_Click);
            // 
            // Delay
            // 
            this.Delay.AutoSize = true;
            this.Delay.Location = new System.Drawing.Point(10, 108);
            this.Delay.Name = "Delay";
            this.Delay.Size = new System.Drawing.Size(51, 13);
            this.Delay.TabIndex = 4;
            this.Delay.Text = "Delay(us)";
            // 
            // LoopTimer
            // 
            this.LoopTimer.AutoSize = true;
            this.LoopTimer.Location = new System.Drawing.Point(10, 79);
            this.LoopTimer.Name = "LoopTimer";
            this.LoopTimer.Size = new System.Drawing.Size(77, 13);
            this.LoopTimer.TabIndex = 3;
            this.LoopTimer.Text = "Loop Timer(us)";
            // 
            // SoftTriggerFire
            // 
            this.SoftTriggerFire.Location = new System.Drawing.Point(129, 17);
            this.SoftTriggerFire.Name = "SoftTriggerFire";
            this.SoftTriggerFire.Size = new System.Drawing.Size(124, 25);
            this.SoftTriggerFire.TabIndex = 2;
            this.SoftTriggerFire.Text = "Soft Trigger Fire";
            this.SoftTriggerFire.UseVisualStyleBackColor = true;
            this.SoftTriggerFire.Click += new System.EventHandler(this.SoftTriggerFire_Click);
            // 
            // LoopTrigger
            // 
            this.LoopTrigger.AutoSize = true;
            this.LoopTrigger.Location = new System.Drawing.Point(11, 46);
            this.LoopTrigger.Name = "LoopTrigger";
            this.LoopTrigger.Size = new System.Drawing.Size(83, 17);
            this.LoopTrigger.TabIndex = 1;
            this.LoopTrigger.Text = "LoopTrigger";
            this.LoopTrigger.UseVisualStyleBackColor = true;
            this.LoopTrigger.CheckedChanged += new System.EventHandler(this.LoopTrigger_CheckedChanged);
            // 
            // TriggerMode
            // 
            this.TriggerMode.AutoSize = true;
            this.TriggerMode.Location = new System.Drawing.Point(11, 22);
            this.TriggerMode.Name = "TriggerMode";
            this.TriggerMode.Size = new System.Drawing.Size(86, 17);
            this.TriggerMode.TabIndex = 0;
            this.TriggerMode.Text = "TriggerMode";
            this.TriggerMode.UseVisualStyleBackColor = true;
            this.TriggerMode.CheckedChanged += new System.EventHandler(this.TriggerMode_CheckedChanged);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.EditFilter);
            this.groupBox2.Controls.Add(this.FilterApply);
            this.groupBox2.Controls.Add(this.label5);
            this.groupBox2.Controls.Add(this.InputSignalTypeCombo);
            this.groupBox2.Controls.Add(this.InputIOCombo);
            this.groupBox2.Controls.Add(this.InputSignalType);
            this.groupBox2.Controls.Add(this.InputIO);
            this.groupBox2.Controls.Add(this.EnableIn);
            this.groupBox2.Location = new System.Drawing.Point(7, 361);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(259, 143);
            this.groupBox2.TabIndex = 20;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Ext Trigger In";
            // 
            // EditFilter
            // 
            this.EditFilter.Location = new System.Drawing.Point(123, 106);
            this.EditFilter.Maximum = new decimal(new int[] {
            99999999,
            0,
            0,
            0});
            this.EditFilter.Name = "EditFilter";
            this.EditFilter.Size = new System.Drawing.Size(57, 20);
            this.EditFilter.TabIndex = 23;
            // 
            // FilterApply
            // 
            this.FilterApply.Location = new System.Drawing.Point(187, 106);
            this.FilterApply.Name = "FilterApply";
            this.FilterApply.Size = new System.Drawing.Size(66, 25);
            this.FilterApply.TabIndex = 7;
            this.FilterApply.Text = "Apply";
            this.FilterApply.UseVisualStyleBackColor = true;
            this.FilterApply.Click += new System.EventHandler(this.FilterApply_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(10, 111);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(71, 13);
            this.label5.TabIndex = 5;
            this.label5.Text = "Jitter Filter(us)";
            // 
            // InputSignalTypeCombo
            // 
            this.InputSignalTypeCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.InputSignalTypeCombo.FormattingEnabled = true;
            this.InputSignalTypeCombo.Location = new System.Drawing.Point(152, 76);
            this.InputSignalTypeCombo.Name = "InputSignalTypeCombo";
            this.InputSignalTypeCombo.Size = new System.Drawing.Size(100, 21);
            this.InputSignalTypeCombo.TabIndex = 4;
            this.InputSignalTypeCombo.SelectedIndexChanged += new System.EventHandler(this.InputSignalTypeCombo_SelectedIndexChanged);
            // 
            // InputIOCombo
            // 
            this.InputIOCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.InputIOCombo.FormattingEnabled = true;
            this.InputIOCombo.Location = new System.Drawing.Point(152, 48);
            this.InputIOCombo.Name = "InputIOCombo";
            this.InputIOCombo.Size = new System.Drawing.Size(100, 21);
            this.InputIOCombo.TabIndex = 3;
            this.InputIOCombo.SelectedIndexChanged += new System.EventHandler(this.InputIOCombo_SelectedIndexChanged);
            // 
            // InputSignalType
            // 
            this.InputSignalType.AutoSize = true;
            this.InputSignalType.Location = new System.Drawing.Point(10, 81);
            this.InputSignalType.Name = "InputSignalType";
            this.InputSignalType.Size = new System.Drawing.Size(90, 13);
            this.InputSignalType.TabIndex = 2;
            this.InputSignalType.Text = "Input Signal Type";
            // 
            // InputIO
            // 
            this.InputIO.AutoSize = true;
            this.InputIO.Location = new System.Drawing.Point(10, 52);
            this.InputIO.Name = "InputIO";
            this.InputIO.Size = new System.Drawing.Size(45, 13);
            this.InputIO.TabIndex = 1;
            this.InputIO.Text = "Input IO";
            // 
            // EnableIn
            // 
            this.EnableIn.AutoSize = true;
            this.EnableIn.Location = new System.Drawing.Point(11, 23);
            this.EnableIn.Name = "EnableIn";
            this.EnableIn.Size = new System.Drawing.Size(59, 17);
            this.EnableIn.TabIndex = 0;
            this.EnableIn.Text = "Enable";
            this.EnableIn.UseVisualStyleBackColor = true;
            this.EnableIn.CheckedChanged += new System.EventHandler(this.EnableIn_CheckedChanged);
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.OutputSignalType);
            this.groupBox3.Controls.Add(this.OutIOCombo);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label8);
            this.groupBox3.Controls.Add(this.EnableOut);
            this.groupBox3.Location = new System.Drawing.Point(7, 511);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(259, 101);
            this.groupBox3.TabIndex = 21;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Ext Strobe Out";
            // 
            // OutputSignalType
            // 
            this.OutputSignalType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.OutputSignalType.FormattingEnabled = true;
            this.OutputSignalType.Location = new System.Drawing.Point(151, 66);
            this.OutputSignalType.Name = "OutputSignalType";
            this.OutputSignalType.Size = new System.Drawing.Size(100, 21);
            this.OutputSignalType.TabIndex = 4;
            this.OutputSignalType.SelectedIndexChanged += new System.EventHandler(this.OutputSignalType_SelectedIndexChanged);
            // 
            // OutIOCombo
            // 
            this.OutIOCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.OutIOCombo.FormattingEnabled = true;
            this.OutIOCombo.Location = new System.Drawing.Point(151, 38);
            this.OutIOCombo.Name = "OutIOCombo";
            this.OutIOCombo.Size = new System.Drawing.Size(100, 21);
            this.OutIOCombo.TabIndex = 3;
            this.OutIOCombo.SelectedIndexChanged += new System.EventHandler(this.OutIOCombo_SelectedIndexChanged);
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(10, 70);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(98, 13);
            this.label7.TabIndex = 2;
            this.label7.Text = "Output Signal Type";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(10, 47);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(53, 13);
            this.label8.TabIndex = 1;
            this.label8.Text = "Output IO";
            // 
            // EnableOut
            // 
            this.EnableOut.AutoSize = true;
            this.EnableOut.Location = new System.Drawing.Point(11, 24);
            this.EnableOut.Name = "EnableOut";
            this.EnableOut.Size = new System.Drawing.Size(59, 17);
            this.EnableOut.TabIndex = 0;
            this.EnableOut.Text = "Enable";
            this.EnableOut.UseVisualStyleBackColor = true;
            this.EnableOut.CheckedChanged += new System.EventHandler(this.EnableOut_CheckedChanged);
            // 
            // pictureBoxMain
            // 
            this.pictureBoxMain.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBoxMain.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.pictureBoxMain.Location = new System.Drawing.Point(272, 118);
            this.pictureBoxMain.Name = "pictureBoxMain";
            this.pictureBoxMain.Size = new System.Drawing.Size(804, 537);
            this.pictureBoxMain.TabIndex = 22;
            this.pictureBoxMain.TabStop = false;
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel4,
            this.toolStripStatusLabel1,
            this.toolStripStatusLabel2,
            this.toolStripStatusLabel3});
            this.statusStrip1.Location = new System.Drawing.Point(0, 758);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(1084, 22);
            this.statusStrip1.TabIndex = 27;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel4
            // 
            this.toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.Size = new System.Drawing.Size(69, 17);
            this.toolStripStatusLabel4.Text = "Powered by";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(30, 17);
            this.toolStripStatusLabel1.Text = "RSA";
            // 
            // toolStripStatusLabel2
            // 
            this.toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            this.toolStripStatusLabel2.Size = new System.Drawing.Size(10, 17);
            this.toolStripStatusLabel2.Text = "|";
            // 
            // toolStripStatusLabel3
            // 
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(50, 17);
            this.toolStripStatusLabel3.Text = "Ver 0.0.1";
            // 
            // textBox1
            // 
            this.textBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox1.Font = new System.Drawing.Font("B Nazanin", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.textBox1.Location = new System.Drawing.Point(3, 16);
            this.textBox1.Multiline = true;
            this.textBox1.Name = "textBox1";
            this.textBox1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.textBox1.Size = new System.Drawing.Size(798, 68);
            this.textBox1.TabIndex = 28;
            this.textBox1.Text = "آدرس گیرنده";
            // 
            // groupBox4
            // 
            this.groupBox4.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox4.Controls.Add(this.textBox1);
            this.groupBox4.Location = new System.Drawing.Point(272, 662);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(804, 87);
            this.groupBox4.TabIndex = 29;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Persian OCR result address:";
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.SystemColors.ControlLight;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Font = new System.Drawing.Font("B Titr", 27.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.label1.Location = new System.Drawing.Point(3, 16);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(253, 109);
            this.label1.TabIndex = 30;
            this.label1.Text = "منطقه";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // menuStrip1
            // 
            this.menuStrip1.BackColor = System.Drawing.Color.LightGray;
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.فایلToolStripMenuItem,
            this.ابزارToolStripMenuItem,
            this.کمکToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 80);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(1084, 24);
            this.menuStrip1.TabIndex = 251;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // فایلToolStripMenuItem
            // 
            this.فایلToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ذخیرهگزارشدراکسلToolStripMenuItem,
            this.toolStripMenuItem3,
            this.خروجToolStripMenuItem});
            this.فایلToolStripMenuItem.Name = "فایلToolStripMenuItem";
            this.فایلToolStripMenuItem.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.فایلToolStripMenuItem.Size = new System.Drawing.Size(49, 20);
            this.فایلToolStripMenuItem.Text = "File";
            // 
            // ذخیرهگزارشدراکسلToolStripMenuItem
            // 
            this.ذخیرهگزارشدراکسلToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("ذخیرهگزارشدراکسلToolStripMenuItem.Image")));
            this.ذخیرهگزارشدراکسلToolStripMenuItem.Name = "ذخیرهگزارشدراکسلToolStripMenuItem";
            this.ذخیرهگزارشدراکسلToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.ذخیرهگزارشدراکسلToolStripMenuItem.Text = "ذخیره گزارش در اکسل";
            // 
            // toolStripMenuItem3
            // 
            this.toolStripMenuItem3.Name = "toolStripMenuItem3";
            this.toolStripMenuItem3.Size = new System.Drawing.Size(177, 6);
            // 
            // خروجToolStripMenuItem
            // 
            this.خروجToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("خروجToolStripMenuItem.Image")));
            this.خروجToolStripMenuItem.Name = "خروجToolStripMenuItem";
            this.خروجToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.خروجToolStripMenuItem.Text = "خروج";
            // 
            // ابزارToolStripMenuItem
            // 
            this.ابزارToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.تستارتباطباEcourierToolStripMenuItem,
            this.toolStripMenuItem1,
            this.menuLog,
            this.پاککردنلاگترازوToolStripMenuItem,
            this.toolStripMenuItem2,
            this.فایلهایپیکربندیToolStripMenuItem,
            this.toolStripMenuItem4,
            this.صفرکردنشمارندهToolStripMenuItem,
            this.toolNotMazadCounter});
            this.ابزارToolStripMenuItem.Name = "ابزارToolStripMenuItem";
            this.ابزارToolStripMenuItem.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.ابزارToolStripMenuItem.Size = new System.Drawing.Size(58, 20);
            this.ابزارToolStripMenuItem.Text = "Tools";
            // 
            // تستارتباطباEcourierToolStripMenuItem
            // 
            this.تستارتباطباEcourierToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("تستارتباطباEcourierToolStripMenuItem.Image")));
            this.تستارتباطباEcourierToolStripMenuItem.Name = "تستارتباطباEcourierToolStripMenuItem";
            this.تستارتباطباEcourierToolStripMenuItem.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.تستارتباطباEcourierToolStripMenuItem.Size = new System.Drawing.Size(243, 22);
            this.تستارتباطباEcourierToolStripMenuItem.Text = "تست ارتباط با e-courier";
            // 
            // toolStripMenuItem1
            // 
            this.toolStripMenuItem1.Name = "toolStripMenuItem1";
            this.toolStripMenuItem1.Size = new System.Drawing.Size(240, 6);
            // 
            // menuLog
            // 
            this.menuLog.Image = ((System.Drawing.Image)(resources.GetObject("menuLog.Image")));
            this.menuLog.Name = "menuLog";
            this.menuLog.Size = new System.Drawing.Size(243, 22);
            this.menuLog.Text = "نمایش لاگ ترازو";
            // 
            // پاککردنلاگترازوToolStripMenuItem
            // 
            this.پاککردنلاگترازوToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("پاککردنلاگترازوToolStripMenuItem.Image")));
            this.پاککردنلاگترازوToolStripMenuItem.Name = "پاککردنلاگترازوToolStripMenuItem";
            this.پاککردنلاگترازوToolStripMenuItem.Size = new System.Drawing.Size(243, 22);
            this.پاککردنلاگترازوToolStripMenuItem.Text = "پاک کردن لاگ ترازو";
            // 
            // toolStripMenuItem2
            // 
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new System.Drawing.Size(240, 6);
            // 
            // فایلهایپیکربندیToolStripMenuItem
            // 
            this.فایلهایپیکربندیToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.دیتابیسToolStripMenuItem,
            this.تنظیماتToolStripMenuItem});
            this.فایلهایپیکربندیToolStripMenuItem.Name = "فایلهایپیکربندیToolStripMenuItem";
            this.فایلهایپیکربندیToolStripMenuItem.Size = new System.Drawing.Size(243, 22);
            this.فایلهایپیکربندیToolStripMenuItem.Text = "فایل های پیکربندی";
            // 
            // دیتابیسToolStripMenuItem
            // 
            this.دیتابیسToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("دیتابیسToolStripMenuItem.Image")));
            this.دیتابیسToolStripMenuItem.Name = "دیتابیسToolStripMenuItem";
            this.دیتابیسToolStripMenuItem.Size = new System.Drawing.Size(138, 22);
            this.دیتابیسToolStripMenuItem.Text = "پایگاه داده ها";
            // 
            // تنظیماتToolStripMenuItem
            // 
            this.تنظیماتToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("تنظیماتToolStripMenuItem.Image")));
            this.تنظیماتToolStripMenuItem.Name = "تنظیماتToolStripMenuItem";
            this.تنظیماتToolStripMenuItem.Size = new System.Drawing.Size(138, 22);
            this.تنظیماتToolStripMenuItem.Text = "تنظیمات";
            // 
            // toolStripMenuItem4
            // 
            this.toolStripMenuItem4.Name = "toolStripMenuItem4";
            this.toolStripMenuItem4.Size = new System.Drawing.Size(240, 6);
            // 
            // صفرکردنشمارندهToolStripMenuItem
            // 
            this.صفرکردنشمارندهToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("صفرکردنشمارندهToolStripMenuItem.Image")));
            this.صفرکردنشمارندهToolStripMenuItem.Name = "صفرکردنشمارندهToolStripMenuItem";
            this.صفرکردنشمارندهToolStripMenuItem.Size = new System.Drawing.Size(243, 22);
            this.صفرکردنشمارندهToolStripMenuItem.Text = "صفر کردن شمارنده";
            // 
            // toolNotMazadCounter
            // 
            this.toolNotMazadCounter.Checked = true;
            this.toolNotMazadCounter.CheckState = System.Windows.Forms.CheckState.Checked;
            this.toolNotMazadCounter.Name = "toolNotMazadCounter";
            this.toolNotMazadCounter.Size = new System.Drawing.Size(243, 22);
            this.toolNotMazadCounter.Text = "عدم رشد شمارنده با بسته‌های مازاد";
            // 
            // کمکToolStripMenuItem
            // 
            this.کمکToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.دربارهماToolStripMenuItem});
            this.کمکToolStripMenuItem.Name = "کمکToolStripMenuItem";
            this.کمکToolStripMenuItem.Padding = new System.Windows.Forms.Padding(10, 0, 10, 0);
            this.کمکToolStripMenuItem.Size = new System.Drawing.Size(56, 20);
            this.کمکToolStripMenuItem.Text = "Help";
            // 
            // دربارهماToolStripMenuItem
            // 
            this.دربارهماToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("دربارهماToolStripMenuItem.Image")));
            this.دربارهماToolStripMenuItem.Name = "دربارهماToolStripMenuItem";
            this.دربارهماToolStripMenuItem.Size = new System.Drawing.Size(180, 22);
            this.دربارهماToolStripMenuItem.Text = "درباره ما";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(16)))), ((int)(((byte)(29)))));
            this.panel1.Controls.Add(this.label13);
            this.panel1.Controls.Add(this.pictureBox3);
            this.panel1.Controls.Add(this.picVolume);
            this.panel1.Controls.Add(this.pictureBox2);
            this.panel1.Controls.Add(this.picLogo);
            this.panel1.Controls.Add(this.picOnOff);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1084, 80);
            this.panel1.TabIndex = 250;
            // 
            // label13
            // 
            this.label13.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label13.BackColor = System.Drawing.Color.LightGray;
            this.label13.Font = new System.Drawing.Font("Tahoma", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(730, 84);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(76, 16);
            this.label13.TabIndex = 258;
            this.label13.Text = "هشدار صوتی";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(715, 12);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(77, 60);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 257;
            this.pictureBox3.TabStop = false;
            // 
            // picVolume
            // 
            this.picVolume.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.picVolume.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picVolume.Image = global::Trigger.Properties.Resources.volume_enable;
            this.picVolume.Location = new System.Drawing.Point(887, 7);
            this.picVolume.Name = "picVolume";
            this.picVolume.Size = new System.Drawing.Size(77, 67);
            this.picVolume.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picVolume.TabIndex = 235;
            this.picVolume.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(806, 9);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(73, 64);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 233;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // picLogo
            // 
            this.picLogo.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picLogo.Image = ((System.Drawing.Image)(resources.GetObject("picLogo.Image")));
            this.picLogo.Location = new System.Drawing.Point(62, 14);
            this.picLogo.Name = "picLogo";
            this.picLogo.Size = new System.Drawing.Size(143, 51);
            this.picLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picLogo.TabIndex = 232;
            this.picLogo.TabStop = false;
            // 
            // picOnOff
            // 
            this.picOnOff.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.picOnOff.Cursor = System.Windows.Forms.Cursors.Hand;
            this.picOnOff.Image = global::Trigger.Properties.Resources.btn_on_red;
            this.picOnOff.Location = new System.Drawing.Point(980, -1);
            this.picOnOff.Name = "picOnOff";
            this.picOnOff.Size = new System.Drawing.Size(89, 80);
            this.picOnOff.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picOnOff.TabIndex = 4;
            this.picOnOff.TabStop = false;
            // 
            // groupBox5
            // 
            this.groupBox5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox5.Controls.Add(this.label1);
            this.groupBox5.Location = new System.Drawing.Point(6, 618);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(259, 128);
            this.groupBox5.TabIndex = 22;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Tehran Zone Identifier";
            // 
            // Trigger
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1084, 780);
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.menuStrip1);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.pictureBoxMain);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.General);
            this.Name = "Trigger";
            this.Text = "RSA OCR + Hw Trigger";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Trigger_FormClosing);
            this.Resize += new System.EventHandler(this.Trigger_Resize);
            this.General.ResumeLayout(false);
            this.General.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerDelay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.TriggerLoop)).EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.EditFilter)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBoxMain)).EndInit();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picVolume)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picLogo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.picOnOff)).EndInit();
            this.groupBox5.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox General;
        private System.Windows.Forms.Button PropertSet;
        private System.Windows.Forms.Button StartPlay;
        private System.Windows.Forms.Button ScanDev;
        private System.Windows.Forms.Button OpenDev;
        private System.Windows.Forms.ComboBox DevNameCombo;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Button ApplyDelay;
        private System.Windows.Forms.Button ApplyLoop;
        private System.Windows.Forms.Label Delay;
        private System.Windows.Forms.Label LoopTimer;
        private System.Windows.Forms.Button SoftTriggerFire;
        private System.Windows.Forms.CheckBox LoopTrigger;
        private System.Windows.Forms.CheckBox TriggerMode;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Button FilterApply;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.ComboBox InputSignalTypeCombo;
        private System.Windows.Forms.ComboBox InputIOCombo;
        private System.Windows.Forms.Label InputSignalType;
        private System.Windows.Forms.Label InputIO;
        private System.Windows.Forms.CheckBox EnableIn;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.ComboBox OutputSignalType;
        private System.Windows.Forms.ComboBox OutIOCombo;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.CheckBox EnableOut;
        private System.Windows.Forms.PictureBox pictureBoxMain;
        private System.Windows.Forms.NumericUpDown TriggerLoop;
        private System.Windows.Forms.NumericUpDown TriggerDelay;
        private System.Windows.Forms.NumericUpDown EditFilter;
		private System.Windows.Forms.CheckBox UserDefinedName;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel4;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel2;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel3;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem فایلToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ذخیرهگزارشدراکسلToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem3;
        private System.Windows.Forms.ToolStripMenuItem خروجToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ابزارToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem تستارتباطباEcourierToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem menuLog;
        private System.Windows.Forms.ToolStripMenuItem پاککردنلاگترازوToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem2;
        private System.Windows.Forms.ToolStripMenuItem فایلهایپیکربندیToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem دیتابیسToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem تنظیماتToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem4;
        private System.Windows.Forms.ToolStripMenuItem صفرکردنشمارندهToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem toolNotMazadCounter;
        private System.Windows.Forms.ToolStripMenuItem کمکToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem دربارهماToolStripMenuItem;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox picVolume;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox picLogo;
        private System.Windows.Forms.PictureBox picOnOff;
        private System.Windows.Forms.GroupBox groupBox5;
    }
}

