namespace ImageAcquisition
{
    partial class ImageAcquisition
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Codes generated by the windows GUI designer.

        /// <summary>
        /// The method that used for supporting designer. 
        /// Do not modify the content of this method by code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ImageAcquisition));
            this.General = new System.Windows.Forms.GroupBox();
            this.UserDefinedName = new System.Windows.Forms.CheckBox();
            this.PropertSet = new System.Windows.Forms.Button();
            this.StartPlay = new System.Windows.Forms.Button();
            this.ScanDev = new System.Windows.Forms.Button();
            this.OpenDev = new System.Windows.Forms.Button();
            this.DevNameCombo = new System.Windows.Forms.ComboBox();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.Configuration = new System.Windows.Forms.GroupBox();
            this.GrabTimeout = new System.Windows.Forms.TextBox();
            this.Label2 = new System.Windows.Forms.Label();
            this.EditWait = new System.Windows.Forms.TextBox();
            this.SoftTrigger = new System.Windows.Forms.CheckBox();
            this.DisplayImage = new System.Windows.Forms.GroupBox();
            this.Display = new System.Windows.Forms.CheckBox();
            this.SaveImage = new System.Windows.Forms.GroupBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.OpenFolder = new System.Windows.Forms.Button();
            this.SelectPath = new System.Windows.Forms.Button();
            this.EditPath = new System.Windows.Forms.TextBox();
            this.Counts = new System.Windows.Forms.Label();
            this.SaveImageCheck = new System.Windows.Forms.CheckBox();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel4 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel2 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.General.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.Configuration.SuspendLayout();
            this.DisplayImage.SuspendLayout();
            this.SaveImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.statusStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // General
            // 
            this.General.Controls.Add(this.UserDefinedName);
            this.General.Controls.Add(this.PropertSet);
            this.General.Controls.Add(this.StartPlay);
            this.General.Controls.Add(this.ScanDev);
            this.General.Controls.Add(this.OpenDev);
            this.General.Controls.Add(this.DevNameCombo);
            this.General.Location = new System.Drawing.Point(10, 150);
            this.General.Name = "General";
            this.General.Size = new System.Drawing.Size(232, 109);
            this.General.TabIndex = 17;
            this.General.TabStop = false;
            this.General.Text = "General";
            // 
            // UserDefinedName
            // 
            this.UserDefinedName.AutoSize = true;
            this.UserDefinedName.Location = new System.Drawing.Point(16, 25);
            this.UserDefinedName.Name = "UserDefinedName";
            this.UserDefinedName.Size = new System.Drawing.Size(119, 17);
            this.UserDefinedName.TabIndex = 23;
            this.UserDefinedName.Text = "User Defined Name";
            this.UserDefinedName.UseVisualStyleBackColor = true;
            this.UserDefinedName.CheckedChanged += new System.EventHandler(this.UserDefineName_CheckedChanged);
            // 
            // PropertSet
            // 
            this.PropertSet.Location = new System.Drawing.Point(152, 76);
            this.PropertSet.Name = "PropertSet";
            this.PropertSet.Size = new System.Drawing.Size(64, 25);
            this.PropertSet.TabIndex = 5;
            this.PropertSet.Text = "Property";
            this.PropertSet.UseVisualStyleBackColor = true;
            this.PropertSet.Click += new System.EventHandler(this.PropertSet_Click);
            // 
            // StartPlay
            // 
            this.StartPlay.Location = new System.Drawing.Point(87, 76);
            this.StartPlay.Name = "StartPlay";
            this.StartPlay.Size = new System.Drawing.Size(57, 25);
            this.StartPlay.TabIndex = 4;
            this.StartPlay.Text = "Start";
            this.StartPlay.UseVisualStyleBackColor = true;
            this.StartPlay.Click += new System.EventHandler(this.StartPlay_Click);
            // 
            // ScanDev
            // 
            this.ScanDev.Location = new System.Drawing.Point(150, 20);
            this.ScanDev.Name = "ScanDev";
            this.ScanDev.Size = new System.Drawing.Size(66, 25);
            this.ScanDev.TabIndex = 3;
            this.ScanDev.Text = "Scan";
            this.ScanDev.UseVisualStyleBackColor = true;
            this.ScanDev.Click += new System.EventHandler(this.ScanDev_Click);
            // 
            // OpenDev
            // 
            this.OpenDev.Location = new System.Drawing.Point(15, 76);
            this.OpenDev.Name = "OpenDev";
            this.OpenDev.Size = new System.Drawing.Size(57, 25);
            this.OpenDev.TabIndex = 2;
            this.OpenDev.Text = "Open";
            this.OpenDev.UseVisualStyleBackColor = true;
            this.OpenDev.Click += new System.EventHandler(this.OpenDev_Click);
            // 
            // DevNameCombo
            // 
            this.DevNameCombo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DevNameCombo.FormattingEnabled = true;
            this.DevNameCombo.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.DevNameCombo.Location = new System.Drawing.Point(15, 49);
            this.DevNameCombo.Name = "DevNameCombo";
            this.DevNameCombo.Size = new System.Drawing.Size(201, 21);
            this.DevNameCombo.TabIndex = 0;
            // 
            // pictureBox
            // 
            this.pictureBox.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.pictureBox.Location = new System.Drawing.Point(249, 6);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(718, 604);
            this.pictureBox.TabIndex = 16;
            this.pictureBox.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(10, 25);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(77, 13);
            this.label1.TabIndex = 18;
            this.label1.Text = "Wait Timer(ms)";
            // 
            // Configuration
            // 
            this.Configuration.Controls.Add(this.GrabTimeout);
            this.Configuration.Controls.Add(this.Label2);
            this.Configuration.Controls.Add(this.EditWait);
            this.Configuration.Controls.Add(this.SoftTrigger);
            this.Configuration.Controls.Add(this.label1);
            this.Configuration.Location = new System.Drawing.Point(13, 267);
            this.Configuration.Name = "Configuration";
            this.Configuration.Size = new System.Drawing.Size(228, 101);
            this.Configuration.TabIndex = 19;
            this.Configuration.TabStop = false;
            this.Configuration.Text = "Configuration";
            // 
            // GrabTimeout
            // 
            this.GrabTimeout.Location = new System.Drawing.Point(126, 50);
            this.GrabTimeout.MaxLength = 8;
            this.GrabTimeout.Name = "GrabTimeout";
            this.GrabTimeout.Size = new System.Drawing.Size(86, 20);
            this.GrabTimeout.TabIndex = 26;
            // 
            // Label2
            // 
            this.Label2.Location = new System.Drawing.Point(10, 53);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(103, 16);
            this.Label2.TabIndex = 25;
            this.Label2.Text = "Grab Timeout(ms)";
            // 
            // EditWait
            // 
            this.EditWait.Location = new System.Drawing.Point(126, 22);
            this.EditWait.MaxLength = 8;
            this.EditWait.Name = "EditWait";
            this.EditWait.Size = new System.Drawing.Size(87, 20);
            this.EditWait.TabIndex = 21;
            // 
            // SoftTrigger
            // 
            this.SoftTrigger.AutoSize = true;
            this.SoftTrigger.Location = new System.Drawing.Point(12, 77);
            this.SoftTrigger.Name = "SoftTrigger";
            this.SoftTrigger.Size = new System.Drawing.Size(81, 17);
            this.SoftTrigger.TabIndex = 19;
            this.SoftTrigger.Text = "Soft Trigger";
            this.SoftTrigger.UseVisualStyleBackColor = true;
            this.SoftTrigger.CheckedChanged += new System.EventHandler(this.SoftTrigger_CheckedChanged);
            // 
            // DisplayImage
            // 
            this.DisplayImage.Controls.Add(this.Display);
            this.DisplayImage.Location = new System.Drawing.Point(13, 374);
            this.DisplayImage.Name = "DisplayImage";
            this.DisplayImage.Size = new System.Drawing.Size(225, 51);
            this.DisplayImage.TabIndex = 21;
            this.DisplayImage.TabStop = false;
            this.DisplayImage.Text = "Display Image";
            // 
            // Display
            // 
            this.Display.AutoSize = true;
            this.Display.Location = new System.Drawing.Point(12, 25);
            this.Display.Name = "Display";
            this.Display.Size = new System.Drawing.Size(60, 17);
            this.Display.TabIndex = 0;
            this.Display.Text = "Display";
            this.Display.UseVisualStyleBackColor = true;
            // 
            // SaveImage
            // 
            this.SaveImage.Controls.Add(this.pictureBox2);
            this.SaveImage.Controls.Add(this.OpenFolder);
            this.SaveImage.Controls.Add(this.SelectPath);
            this.SaveImage.Controls.Add(this.EditPath);
            this.SaveImage.Controls.Add(this.Counts);
            this.SaveImage.Controls.Add(this.SaveImageCheck);
            this.SaveImage.Location = new System.Drawing.Point(13, 432);
            this.SaveImage.Name = "SaveImage";
            this.SaveImage.Size = new System.Drawing.Size(225, 178);
            this.SaveImage.TabIndex = 22;
            this.SaveImage.TabStop = false;
            this.SaveImage.Text = "Save Image";
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(52, 17);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(105, 73);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 28;
            this.pictureBox2.TabStop = false;
            // 
            // OpenFolder
            // 
            this.OpenFolder.Location = new System.Drawing.Point(110, 141);
            this.OpenFolder.Name = "OpenFolder";
            this.OpenFolder.Size = new System.Drawing.Size(101, 25);
            this.OpenFolder.TabIndex = 25;
            this.OpenFolder.Text = "Open Folder";
            this.OpenFolder.UseVisualStyleBackColor = true;
            this.OpenFolder.Click += new System.EventHandler(this.OpenFolder_Click);
            // 
            // SelectPath
            // 
            this.SelectPath.Location = new System.Drawing.Point(10, 141);
            this.SelectPath.Name = "SelectPath";
            this.SelectPath.Size = new System.Drawing.Size(103, 25);
            this.SelectPath.TabIndex = 24;
            this.SelectPath.Text = "Select Path";
            this.SelectPath.UseVisualStyleBackColor = true;
            this.SelectPath.Click += new System.EventHandler(this.SelectPath_Click);
            // 
            // EditPath
            // 
            this.EditPath.Location = new System.Drawing.Point(10, 115);
            this.EditPath.Name = "EditPath";
            this.EditPath.ReadOnly = true;
            this.EditPath.Size = new System.Drawing.Size(201, 20);
            this.EditPath.TabIndex = 23;
            // 
            // Counts
            // 
            this.Counts.AutoSize = true;
            this.Counts.Location = new System.Drawing.Point(147, 94);
            this.Counts.Name = "Counts";
            this.Counts.Size = new System.Drawing.Size(40, 13);
            this.Counts.TabIndex = 1;
            this.Counts.Text = "Counts";
            // 
            // SaveImageCheck
            // 
            this.SaveImageCheck.AutoSize = true;
            this.SaveImageCheck.Checked = true;
            this.SaveImageCheck.CheckState = System.Windows.Forms.CheckState.Checked;
            this.SaveImageCheck.Location = new System.Drawing.Point(11, 92);
            this.SaveImageCheck.Name = "SaveImageCheck";
            this.SaveImageCheck.Size = new System.Drawing.Size(83, 17);
            this.SaveImageCheck.TabIndex = 0;
            this.SaveImageCheck.Text = "Save Image";
            this.SaveImageCheck.UseVisualStyleBackColor = true;
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel4,
            this.toolStripStatusLabel1,
            this.toolStripStatusLabel2,
            this.toolStripStatusLabel3});
            this.statusStrip1.Location = new System.Drawing.Point(0, 621);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(978, 22);
            this.statusStrip1.TabIndex = 27;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel4
            // 
            this.toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.Size = new System.Drawing.Size(69, 17);
            this.toolStripStatusLabel4.Text = "Powered by";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(30, 17);
            this.toolStripStatusLabel1.Text = "RSA";
            // 
            // toolStripStatusLabel2
            // 
            this.toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            this.toolStripStatusLabel2.Size = new System.Drawing.Size(10, 17);
            this.toolStripStatusLabel2.Text = "|";
            // 
            // toolStripStatusLabel3
            // 
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(50, 17);
            this.toolStripStatusLabel3.Text = "Ver 0.0.1";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(65, 6);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(135, 138);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 26;
            this.pictureBox1.TabStop = false;
            // 
            // ImageAcquisition
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(978, 643);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.SaveImage);
            this.Controls.Add(this.DisplayImage);
            this.Controls.Add(this.Configuration);
            this.Controls.Add(this.General);
            this.Controls.Add(this.pictureBox);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "ImageAcquisition";
            this.Text = "RSA ImageAcquisition";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.ImageAcquisition_FormClosing);
            this.Load += new System.EventHandler(this.ImageAcquisition_Load);
            this.Resize += new System.EventHandler(this.ImageAcquisition_Resize);
            this.General.ResumeLayout(false);
            this.General.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.Configuration.ResumeLayout(false);
            this.Configuration.PerformLayout();
            this.DisplayImage.ResumeLayout(false);
            this.DisplayImage.PerformLayout();
            this.SaveImage.ResumeLayout(false);
            this.SaveImage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.GroupBox General;
        private System.Windows.Forms.Button PropertSet;
        private System.Windows.Forms.Button StartPlay;
        private System.Windows.Forms.Button ScanDev;
        private System.Windows.Forms.Button OpenDev;
        private System.Windows.Forms.ComboBox DevNameCombo;
        private System.Windows.Forms.PictureBox pictureBox;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox Configuration;
        private System.Windows.Forms.TextBox EditWait;
        private System.Windows.Forms.CheckBox SoftTrigger;
        private System.Windows.Forms.GroupBox DisplayImage;
        private System.Windows.Forms.CheckBox Display;
        private System.Windows.Forms.GroupBox SaveImage;
        private System.Windows.Forms.Button OpenFolder;
        private System.Windows.Forms.Button SelectPath;
        private System.Windows.Forms.TextBox EditPath;
        private System.Windows.Forms.Label Counts;
        private System.Windows.Forms.CheckBox SaveImageCheck;
		internal System.Windows.Forms.TextBox GrabTimeout;
		internal System.Windows.Forms.Label Label2;
		private System.Windows.Forms.CheckBox UserDefinedName;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel4;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel2;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel3;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
    }
}

