namespace BasicFunction
{
    partial class BasicFunction
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Codes generated by the window designer.

        /// <summary>
        /// The method that used for supporting designer. 
        /// Do not modify the content of this method by code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(BasicFunction));
            this.COMBO_DEVICES = new System.Windows.Forms.ComboBox();
            this.BUTTON_OPEN = new System.Windows.Forms.Button();
            this.BUTTON_SCAN = new System.Windows.Forms.Button();
            this.BUTTON_START = new System.Windows.Forms.Button();
            this.BUTTON_PROPERTY = new System.Windows.Forms.Button();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.BUTTON_SAVE = new System.Windows.Forms.Button();
            this.COMBO_FLICK = new System.Windows.Forms.ComboBox();
            this.General = new System.Windows.Forms.GroupBox();
            this.UserDefinedName = new System.Windows.Forms.CheckBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.CHECK_AEOPERATION = new System.Windows.Forms.CheckBox();
            this.COMBO_AE_MODE = new System.Windows.Forms.ComboBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.AE_Mode = new System.Windows.Forms.Label();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.ExposureTimeApply = new System.Windows.Forms.Button();
            this.ExposureTimeEdit = new System.Windows.Forms.NumericUpDown();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.groupBox11 = new System.Windows.Forms.GroupBox();
            this.GainApply = new System.Windows.Forms.Button();
            this.GainEdit = new System.Windows.Forms.NumericUpDown();
            this.groupBox7 = new System.Windows.Forms.GroupBox();
            this.COMBO_RESOLUTION = new System.Windows.Forms.ComboBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.AWBOnce = new System.Windows.Forms.Button();
            this.AWBEnable = new System.Windows.Forms.CheckBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.statusStrip1 = new System.Windows.Forms.StatusStrip();
            this.toolStripStatusLabel1 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel2 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel3 = new System.Windows.Forms.ToolStripStatusLabel();
            this.toolStripStatusLabel4 = new System.Windows.Forms.ToolStripStatusLabel();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.General.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ExposureTimeEdit)).BeginInit();
            this.groupBox5.SuspendLayout();
            this.groupBox11.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.GainEdit)).BeginInit();
            this.groupBox7.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.statusStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // COMBO_DEVICES
            // 
            this.COMBO_DEVICES.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.COMBO_DEVICES.FormattingEnabled = true;
            this.COMBO_DEVICES.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.COMBO_DEVICES.Location = new System.Drawing.Point(15, 47);
            this.COMBO_DEVICES.Name = "COMBO_DEVICES";
            this.COMBO_DEVICES.Size = new System.Drawing.Size(210, 21);
            this.COMBO_DEVICES.TabIndex = 0;
            // 
            // BUTTON_OPEN
            // 
            this.BUTTON_OPEN.Image = ((System.Drawing.Image)(resources.GetObject("BUTTON_OPEN.Image")));
            this.BUTTON_OPEN.Location = new System.Drawing.Point(15, 76);
            this.BUTTON_OPEN.Name = "BUTTON_OPEN";
            this.BUTTON_OPEN.Size = new System.Drawing.Size(64, 25);
            this.BUTTON_OPEN.TabIndex = 2;
            this.BUTTON_OPEN.UseVisualStyleBackColor = true;
            this.BUTTON_OPEN.Click += new System.EventHandler(this.BUTTON_OPEN_Click);
            // 
            // BUTTON_SCAN
            // 
            this.BUTTON_SCAN.Location = new System.Drawing.Point(159, 16);
            this.BUTTON_SCAN.Name = "BUTTON_SCAN";
            this.BUTTON_SCAN.Size = new System.Drawing.Size(66, 25);
            this.BUTTON_SCAN.TabIndex = 3;
            this.BUTTON_SCAN.Text = "Scan";
            this.BUTTON_SCAN.UseVisualStyleBackColor = true;
            this.BUTTON_SCAN.Click += new System.EventHandler(this.BUTTON_SCAN_Click);
            // 
            // BUTTON_START
            // 
            this.BUTTON_START.Location = new System.Drawing.Point(85, 76);
            this.BUTTON_START.Name = "BUTTON_START";
            this.BUTTON_START.Size = new System.Drawing.Size(63, 25);
            this.BUTTON_START.TabIndex = 4;
            this.BUTTON_START.Text = "Start";
            this.BUTTON_START.UseVisualStyleBackColor = true;
            this.BUTTON_START.Click += new System.EventHandler(this.BUTTON_START_Click);
            // 
            // BUTTON_PROPERTY
            // 
            this.BUTTON_PROPERTY.Location = new System.Drawing.Point(159, 76);
            this.BUTTON_PROPERTY.Name = "BUTTON_PROPERTY";
            this.BUTTON_PROPERTY.Size = new System.Drawing.Size(66, 25);
            this.BUTTON_PROPERTY.TabIndex = 5;
            this.BUTTON_PROPERTY.Text = "Property";
            this.BUTTON_PROPERTY.UseVisualStyleBackColor = true;
            this.BUTTON_PROPERTY.Click += new System.EventHandler(this.BUTTON_PROPERTY_Click);
            // 
            // pictureBox
            // 
            this.pictureBox.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox.BackColor = System.Drawing.SystemColors.ActiveBorder;
            this.pictureBox.Location = new System.Drawing.Point(248, 8);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(829, 713);
            this.pictureBox.TabIndex = 6;
            this.pictureBox.TabStop = false;
            this.pictureBox.Click += new System.EventHandler(this.pictureBox_Click);
            // 
            // BUTTON_SAVE
            // 
            this.BUTTON_SAVE.Image = ((System.Drawing.Image)(resources.GetObject("BUTTON_SAVE.Image")));
            this.BUTTON_SAVE.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BUTTON_SAVE.Location = new System.Drawing.Point(136, 14);
            this.BUTTON_SAVE.Name = "BUTTON_SAVE";
            this.BUTTON_SAVE.Size = new System.Drawing.Size(88, 32);
            this.BUTTON_SAVE.TabIndex = 7;
            this.BUTTON_SAVE.Text = "Shot    ";
            this.BUTTON_SAVE.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BUTTON_SAVE.UseVisualStyleBackColor = true;
            this.BUTTON_SAVE.Click += new System.EventHandler(this.BUTTON_SAVE_Click);
            // 
            // COMBO_FLICK
            // 
            this.COMBO_FLICK.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.COMBO_FLICK.FormattingEnabled = true;
            this.COMBO_FLICK.Location = new System.Drawing.Point(78, 22);
            this.COMBO_FLICK.Name = "COMBO_FLICK";
            this.COMBO_FLICK.Size = new System.Drawing.Size(147, 21);
            this.COMBO_FLICK.TabIndex = 11;
            this.COMBO_FLICK.SelectedIndexChanged += new System.EventHandler(this.COMBO_FLICK_SelectedIndexChanged);
            // 
            // General
            // 
            this.General.Controls.Add(this.UserDefinedName);
            this.General.Controls.Add(this.BUTTON_PROPERTY);
            this.General.Controls.Add(this.BUTTON_START);
            this.General.Controls.Add(this.BUTTON_SCAN);
            this.General.Controls.Add(this.BUTTON_OPEN);
            this.General.Controls.Add(this.COMBO_DEVICES);
            this.General.Location = new System.Drawing.Point(11, 160);
            this.General.Name = "General";
            this.General.Size = new System.Drawing.Size(231, 111);
            this.General.TabIndex = 15;
            this.General.TabStop = false;
            this.General.Text = "General";
            // 
            // UserDefinedName
            // 
            this.UserDefinedName.AutoSize = true;
            this.UserDefinedName.Location = new System.Drawing.Point(15, 22);
            this.UserDefinedName.Name = "UserDefinedName";
            this.UserDefinedName.Size = new System.Drawing.Size(119, 17);
            this.UserDefinedName.TabIndex = 6;
            this.UserDefinedName.Text = "User Defined Name";
            this.UserDefinedName.UseVisualStyleBackColor = true;
            this.UserDefinedName.CheckedChanged += new System.EventHandler(this.UserDefineName_CheckedChanged);
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.BUTTON_SAVE);
            this.groupBox3.Location = new System.Drawing.Point(11, 279);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(231, 52);
            this.groupBox3.TabIndex = 16;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Save Picture";
            // 
            // CHECK_AEOPERATION
            // 
            this.CHECK_AEOPERATION.AutoSize = true;
            this.CHECK_AEOPERATION.Location = new System.Drawing.Point(15, 22);
            this.CHECK_AEOPERATION.Name = "CHECK_AEOPERATION";
            this.CHECK_AEOPERATION.Size = new System.Drawing.Size(76, 17);
            this.CHECK_AEOPERATION.TabIndex = 8;
            this.CHECK_AEOPERATION.Text = "AE Enable";
            this.CHECK_AEOPERATION.UseVisualStyleBackColor = true;
            this.CHECK_AEOPERATION.Click += new System.EventHandler(this.CHECK_AEOPERATION_Click);
            // 
            // COMBO_AE_MODE
            // 
            this.COMBO_AE_MODE.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.COMBO_AE_MODE.FormattingEnabled = true;
            this.COMBO_AE_MODE.Location = new System.Drawing.Point(78, 52);
            this.COMBO_AE_MODE.Name = "COMBO_AE_MODE";
            this.COMBO_AE_MODE.Size = new System.Drawing.Size(147, 21);
            this.COMBO_AE_MODE.TabIndex = 9;
            this.COMBO_AE_MODE.SelectedIndexChanged += new System.EventHandler(this.COMBO_AE_MODE_SelectedIndexChanged);
            this.COMBO_AE_MODE.ImeModeChanged += new System.EventHandler(this.COMBO_AE_MODE_ImeModeChanged);
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.AE_Mode);
            this.groupBox1.Controls.Add(this.COMBO_AE_MODE);
            this.groupBox1.Controls.Add(this.CHECK_AEOPERATION);
            this.groupBox1.Location = new System.Drawing.Point(11, 337);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(231, 84);
            this.groupBox1.TabIndex = 14;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Auto Exposure";
            // 
            // AE_Mode
            // 
            this.AE_Mode.AutoSize = true;
            this.AE_Mode.Location = new System.Drawing.Point(14, 56);
            this.AE_Mode.Name = "AE_Mode";
            this.AE_Mode.Size = new System.Drawing.Size(51, 13);
            this.AE_Mode.TabIndex = 10;
            this.AE_Mode.Text = "AE Mode";
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.ExposureTimeApply);
            this.groupBox4.Controls.Add(this.ExposureTimeEdit);
            this.groupBox4.Location = new System.Drawing.Point(11, 427);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(231, 62);
            this.groupBox4.TabIndex = 17;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Exposure Time(us)";
            // 
            // ExposureTimeApply
            // 
            this.ExposureTimeApply.Location = new System.Drawing.Point(168, 23);
            this.ExposureTimeApply.Name = "ExposureTimeApply";
            this.ExposureTimeApply.Size = new System.Drawing.Size(57, 25);
            this.ExposureTimeApply.TabIndex = 24;
            this.ExposureTimeApply.Text = "Apply";
            this.ExposureTimeApply.UseVisualStyleBackColor = true;
            this.ExposureTimeApply.Click += new System.EventHandler(this.ExposureTimeApply_Click);
            // 
            // ExposureTimeEdit
            // 
            this.ExposureTimeEdit.Increment = new decimal(new int[] {
            100,
            0,
            0,
            0});
            this.ExposureTimeEdit.Location = new System.Drawing.Point(78, 25);
            this.ExposureTimeEdit.Name = "ExposureTimeEdit";
            this.ExposureTimeEdit.Size = new System.Drawing.Size(84, 20);
            this.ExposureTimeEdit.TabIndex = 23;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.COMBO_FLICK);
            this.groupBox5.Location = new System.Drawing.Point(11, 495);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(231, 55);
            this.groupBox5.TabIndex = 19;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Anti Flick";
            // 
            // groupBox11
            // 
            this.groupBox11.Controls.Add(this.GainApply);
            this.groupBox11.Controls.Add(this.GainEdit);
            this.groupBox11.Location = new System.Drawing.Point(11, 557);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new System.Drawing.Size(231, 50);
            this.groupBox11.TabIndex = 20;
            this.groupBox11.TabStop = false;
            this.groupBox11.Text = "Gain(x)";
            // 
            // GainApply
            // 
            this.GainApply.Location = new System.Drawing.Point(168, 17);
            this.GainApply.Name = "GainApply";
            this.GainApply.Size = new System.Drawing.Size(57, 25);
            this.GainApply.TabIndex = 26;
            this.GainApply.Text = "Apply";
            this.GainApply.UseVisualStyleBackColor = true;
            this.GainApply.Click += new System.EventHandler(this.GainApply_Click);
            // 
            // GainEdit
            // 
            this.GainEdit.Location = new System.Drawing.Point(78, 18);
            this.GainEdit.Name = "GainEdit";
            this.GainEdit.Size = new System.Drawing.Size(84, 20);
            this.GainEdit.TabIndex = 24;
            // 
            // groupBox7
            // 
            this.groupBox7.Controls.Add(this.COMBO_RESOLUTION);
            this.groupBox7.Location = new System.Drawing.Point(11, 672);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new System.Drawing.Size(231, 55);
            this.groupBox7.TabIndex = 21;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Preset Roi";
            // 
            // COMBO_RESOLUTION
            // 
            this.COMBO_RESOLUTION.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.COMBO_RESOLUTION.FormattingEnabled = true;
            this.COMBO_RESOLUTION.Location = new System.Drawing.Point(78, 25);
            this.COMBO_RESOLUTION.Name = "COMBO_RESOLUTION";
            this.COMBO_RESOLUTION.Size = new System.Drawing.Size(146, 21);
            this.COMBO_RESOLUTION.TabIndex = 11;
            this.COMBO_RESOLUTION.SelectedIndexChanged += new System.EventHandler(this.COMBO_RESOLUTION_SelectedIndexChanged);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.AWBOnce);
            this.groupBox2.Controls.Add(this.AWBEnable);
            this.groupBox2.Location = new System.Drawing.Point(11, 614);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(231, 52);
            this.groupBox2.TabIndex = 23;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "White Balance";
            // 
            // AWBOnce
            // 
            this.AWBOnce.Location = new System.Drawing.Point(113, 17);
            this.AWBOnce.Name = "AWBOnce";
            this.AWBOnce.Size = new System.Drawing.Size(112, 25);
            this.AWBOnce.TabIndex = 1;
            this.AWBOnce.Text = "White Balance";
            this.AWBOnce.UseVisualStyleBackColor = true;
            this.AWBOnce.Click += new System.EventHandler(this.AWBOnce_Click);
            // 
            // AWBEnable
            // 
            this.AWBEnable.AutoSize = true;
            this.AWBEnable.Location = new System.Drawing.Point(15, 23);
            this.AWBEnable.Name = "AWBEnable";
            this.AWBEnable.Size = new System.Drawing.Size(87, 17);
            this.AWBEnable.TabIndex = 0;
            this.AWBEnable.Text = "AWB Enable";
            this.AWBEnable.UseVisualStyleBackColor = true;
            this.AWBEnable.CheckedChanged += new System.EventHandler(this.AWBEnable_CheckedChanged);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(11, 8);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(225, 146);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 24;
            this.pictureBox1.TabStop = false;
            // 
            // statusStrip1
            // 
            this.statusStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripStatusLabel4,
            this.toolStripStatusLabel1,
            this.toolStripStatusLabel2,
            this.toolStripStatusLabel3});
            this.statusStrip1.Location = new System.Drawing.Point(0, 725);
            this.statusStrip1.Name = "statusStrip1";
            this.statusStrip1.Size = new System.Drawing.Size(1081, 22);
            this.statusStrip1.TabIndex = 25;
            this.statusStrip1.Text = "statusStrip1";
            // 
            // toolStripStatusLabel1
            // 
            this.toolStripStatusLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            this.toolStripStatusLabel1.Size = new System.Drawing.Size(30, 17);
            this.toolStripStatusLabel1.Text = "RSA";
            // 
            // toolStripStatusLabel2
            // 
            this.toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            this.toolStripStatusLabel2.Size = new System.Drawing.Size(10, 17);
            this.toolStripStatusLabel2.Text = "|";
            // 
            // toolStripStatusLabel3
            // 
            this.toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            this.toolStripStatusLabel3.Size = new System.Drawing.Size(50, 17);
            this.toolStripStatusLabel3.Text = "Ver 0.0.1";
            // 
            // toolStripStatusLabel4
            // 
            this.toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            this.toolStripStatusLabel4.Size = new System.Drawing.Size(69, 17);
            this.toolStripStatusLabel4.Text = "Powered by";
            // 
            // BasicFunction
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1081, 747);
            this.Controls.Add(this.statusStrip1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox7);
            this.Controls.Add(this.groupBox11);
            this.Controls.Add(this.groupBox5);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.General);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.pictureBox);
            this.Name = "BasicFunction";
            this.Text = "RSA BasicFunction OCR - Demo";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.BasicFunction_FormClosing);
            this.Resize += new System.EventHandler(this.BasicFunction_Resize);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.General.ResumeLayout(false);
            this.General.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ExposureTimeEdit)).EndInit();
            this.groupBox5.ResumeLayout(false);
            this.groupBox11.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.GainEdit)).EndInit();
            this.groupBox7.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.statusStrip1.ResumeLayout(false);
            this.statusStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ComboBox COMBO_DEVICES;
        private System.Windows.Forms.Button BUTTON_OPEN;
        private System.Windows.Forms.Button BUTTON_SCAN;
        private System.Windows.Forms.Button BUTTON_START;
        private System.Windows.Forms.Button BUTTON_PROPERTY;
		private System.Windows.Forms.PictureBox pictureBox;
		private System.Windows.Forms.Button BUTTON_SAVE;
        private System.Windows.Forms.ComboBox COMBO_FLICK;
        private System.Windows.Forms.GroupBox General;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.CheckBox CHECK_AEOPERATION;
        private System.Windows.Forms.ComboBox COMBO_AE_MODE;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label AE_Mode;
		private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.GroupBox groupBox5;
		private System.Windows.Forms.GroupBox groupBox11;
        private System.Windows.Forms.GroupBox groupBox7;
		private System.Windows.Forms.ComboBox COMBO_RESOLUTION;
		private System.Windows.Forms.Button ExposureTimeApply;
		private System.Windows.Forms.NumericUpDown ExposureTimeEdit;
		private System.Windows.Forms.Button GainApply;
		private System.Windows.Forms.NumericUpDown GainEdit;
		private System.Windows.Forms.GroupBox groupBox2;
		private System.Windows.Forms.Button AWBOnce;
		private System.Windows.Forms.CheckBox AWBEnable;
		private System.Windows.Forms.CheckBox UserDefinedName;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.StatusStrip statusStrip1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel1;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel2;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel3;
        private System.Windows.Forms.ToolStripStatusLabel toolStripStatusLabel4;
    }
}

